sudo: false

# http://docs.haskellstack.org/en/stable/travis_ci/#container-infrastructure
cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=/opt/ghc/7.8.4/bin:$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4

script:
  - stack --no-terminal --skip-ghc-check test
